# frozen_string_literal: true

Vagrant.configure("2") do |config|
  config.vm.synced_folder "../..", "/vagrant/migrate-to-oracle-linux"

  boxes = {
    "almalinux-8" => "almalinux/8",
    "almalinux-9" => "almalinux/9",
    "rocky-8" => "rockylinux/8",
    "rocky-9" => "rockylinux/9"
  }

  boxes.each do |name, box|
    config.vm.define name do |node|
      node.vm.box = box
      node.vm.hostname = name
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
      node.vm.provision "shell", privileged: true, inline: <<~SHELL
        set -eux
        cd /vagrant/migrate-to-oracle-linux
        bash -n migrate-to-oracle-linux.sh
        ./migrate-to-oracle-linux.sh --dry-run --no-reboot-check
      SHELL
    end
  end
end
